export const clientsData = [
  {
    id: 1,
    clientId: "Cli-001",
    clientName: "Michael Walker",
    clientRole: "CEO",
    clientAvatar: "/assets/img/users/user-39.jpg",
    companyName: "BrightWave Innovations",
    email: "michael@example.com",
    phone: "(163) 2459 315",
    mobile: "9876543210",
    status: "Active",
    contactPerson: "Sarah Johnson",
    customerType: "B2B",
    clientType: "Direct",
    accountManager: "Hendry Milner",
    createdAt: "10 Jan 2024"
  },
  {
    id: 2,
    clientId: "Cli-002",
    clientName: "Sophie Headrick",
    clientRole: "Manager",
    clientAvatar: "/assets/img/users/user-40.jpg",
    companyName: "Stellar Dynamics",
    email: "sophie@example.com",
    phone: "(146) 1249 296",
    mobile: "9876543211",
    status: "Active",
    contactPerson: "David Smith",
    customerType: "B2C",
    clientType: "Partner",
    accountManager: "Guilory Berggren",
    createdAt: "15 Feb 2024"
  },
  {
    id: 3,
    clientId: "Cli-003",
    clientName: "Cameron Drake",
    clientRole: "Director",
    clientAvatar: "/assets/img/users/user-41.jpg",
    companyName: "Quantum Nexus",
    email: "cameron@example.com",
    phone: "(135) 3489 516",
    mobile: "9876543212",
    status: "Active",
    contactPerson: "Emily Brown",
    customerType: "Enterprise",
    clientType: "Direct",
    accountManager: "Jami Carlile",
    createdAt: "22 Mar 2024"
  },
  {
    id: 4,
    clientId: "Cli-004",
    clientName: "Doris Crowley",
    clientRole: "Consultant",
    clientAvatar: "/assets/img/users/user-42.jpg",
    companyName: "EcoVision Enterprises",
    email: "doris@example.com",
    phone: "(158) 3459 596",
    mobile: "9876543213",
    status: "Active",
    contactPerson: "Michael Davis",
    customerType: "B2B",
    clientType: "Agency",
    accountManager: "Theresa Nelson",
    createdAt: "05 Apr 2024"
  },
  {
    id: 5,
    clientId: "Cli-005",
    clientName: "Thomas Bordelon",
    clientRole: "Manager",
    clientAvatar: "/assets/img/users/user-44.jpg",
    companyName: "Aurora Technologies",
    email: "thomas@example.com",
    phone: "(196) 4862 196",
    mobile: "9876543214",
    status: "Active",
    contactPerson: "Jessica Wilson",
    customerType: "SMB",
    clientType: "Direct",
    accountManager: "Smith Cooper",
    createdAt: "12 May 2024"
  },
  {
    id: 6,
    clientId: "Cli-006",
    clientName: "Kathleen Gutierrez",
    clientRole: "Director",
    clientAvatar: "/assets/img/users/user-45.jpg",
    companyName: "BlueSky Ventures",
    email: "kathleen@example.com",
    phone: "(163) 6498 256",
    mobile: "9876543215",
    status: "Active",
    contactPerson: "Daniel Taylor",
    customerType: "Enterprise",
    clientType: "Partner",
    accountManager: "Martin Lewis",
    createdAt: "18 Jun 2024"
  },
  {
    id: 7,
    clientId: "Cli-007",
    clientName: "Bruce Wright",
    clientRole: "CEO",
    clientAvatar: "/assets/img/users/user-46.jpg",
    companyName: "TerraFusion Energy",
    email: "bruce@example.com",
    phone: "(154) 6481 075",
    mobile: "9876543216",
    status: "Active",
    contactPerson: "Laura Martinez",
    customerType: "B2C",
    clientType: "Direct",
    accountManager: "Newell Egan",
    createdAt: "25 Jul 2024"
  },
  {
    id: 8,
    clientId: "Cli-008",
    clientName: "Estelle Morgan",
    clientRole: "Manager",
    clientAvatar: "/assets/img/users/user-47.jpg",
    companyName: "UrbanPulse Design",
    email: "estelle@example.com",
    phone: "(184) 6348 195",
    mobile: "9876543217",
    status: "Inactive",
    contactPerson: "James Anderson",
    customerType: "B2B",
    clientType: "Agency",
    accountManager: "Janet Carlson",
    createdAt: "30 Aug 2024"
  },
  {
    id: 9,
    clientId: "Cli-009",
    clientName: "Stephen Dias",
    clientRole: "CEO",
    clientAvatar: "/assets/img/users/user-48.jpg",
    companyName: "Nimbus Networks",
    email: "stephen@example.com",
    phone: "(175) 2496 125",
    mobile: "9876543218",
    status: "Active",
    contactPerson: "Mary Thomas",
    customerType: "SMB",
    clientType: "Direct",
    accountManager: "Craig Brown",
    createdAt: "14 Sep 2024"
  },
  {
    id: 10,
    clientId: "Cli-010",
    clientName: "Angela Thomas",
    clientRole: "Consultant",
    clientAvatar: "/assets/img/users/user-43.jpg",
    companyName: "Epicurean Delights",
    email: "angela@example.com",
    phone: "(132) 3145 977",
    mobile: "9876543219",
    status: "Active",
    contactPerson: "Robert Jackson",
    customerType: "Enterprise",
    clientType: "Partner",
    accountManager: "Daniel Byrne",
    createdAt: "21 Oct 2024"
  }
];
