export const contactsData = [
  {
    id: 1,
    name: "Darlee Robertson",
    role: "Facility Manager",
    avatar: "/assets/img/users/user-49.jpg",
    email: "darlee@example.com",
    phone: "(163) 2459 315",
    location: "Germany",
    rating: "4.2",
    owner: "Hendry Milner",
    status: "Active",
    company: "BrightWave Innovations",
    department: "Operations",
    createdDate: "14 Jan 2024"
  },
  {
    id: 2,
    name: "Sharon Roy",
    role: "Installer",
    avatar: "/assets/img/users/user-50.jpg",
    email: "sharon@example.com",
    phone: "(146) 1249 296",
    location: "USA",
    rating: "5.0",
    owner: "Guilory Berggren",
    status: "Active",
    company: "Stellar Dynamics",
    department: "Installation",
    createdDate: "21 Jan 2024"
  },
  {
    id: 3,
    name: "Vaughan Lewis",
    role: "Senior Manager",
    avatar: "/assets/img/users/user-51.jpg",
    email: "vaughan@example.com",
    phone: "(135) 3489 516",
    location: "Canada",
    rating: "3.5",
    owner: "Jami Carlile",
    status: "Active",
    company: "Quantum Nexus",
    department: "Management",
    createdDate: "20 Feb 2024"
  },
  {
    id: 4,
    name: "Jessica Louise",
    role: "Test Engineer",
    avatar: "/assets/img/users/user-02.jpg",
    email: "jessica@example.com",
    phone: "(158) 3459 596",
    location: "India",
    rating: "4.5",
    owner: "Theresa Nelson",
    status: "Active",
    company: "EcoVision Enterprises",
    department: "Quality Assurance",
    createdDate: "15 Mar 2024"
  },
  {
    id: 5,
    name: "Carol Thomas",
    role: "UI /UX Designer",
    avatar: "/assets/img/users/user-52.jpg",
    email: "carol@example.com",
    phone: "(196) 4862 196",
    location: "China",
    rating: "4.7",
    owner: "Smith Cooper",
    status: "Active",
    company: "Aurora Technologies",
    department: "Design",
    createdDate: "12 Apr 2024"
  },
  {
    id: 6,
    name: "Dawn Castillo",
    role: "Technician",
    avatar: "/assets/img/users/user-57.jpg",
    email: "dawn@example.com",
    phone: "(163) 6498 256",
    location: "Japan",
    rating: "5.0",
    owner: "Martin Lewis",
    status: "Active",
    company: "BlueSky Ventures",
    department: "Maintenance",
    createdDate: "20 Apr 2024"
  },
  {
    id: 7,
    name: "Rachel Hampton",
    role: "Software Developer",
    avatar: "/assets/img/users/user-54.jpg",
    email: "rachel@example.com",
    phone: "(154) 6481 075",
    location: "Indonesia",
    rating: "3.1",
    owner: "Newell Egan",
    status: "Active",
    company: "TerraFusion Energy",
    department: "Engineering",
    createdDate: "06 Jul 2024"
  },
  {
    id: 8,
    name: "Jonelle Curtiss",
    role: "Supervisor",
    avatar: "/assets/img/users/user-56.jpg",
    email: "jonella@example.com",
    phone: "(184) 6348 195",
    location: "Cuba",
    rating: "5.0",
    owner: "Janet Carlson",
    status: "Active",
    company: "UrbanPulse Design",
    department: "Management",
    createdDate: "02 Sep 2024"
  },
  {
    id: 9,
    name: "Jonathan Smith",
    role: "Team Lead Dev",
    avatar: "/assets/img/users/user-26.jpg",
    email: "jonathan@example.com",
    phone: "(175) 2496 125",
    location: "Israel",
    rating: "2.7",
    owner: "Craig Brown",
    status: "Active",
    company: "Nimbus Networks",
    department: "Engineering",
    createdDate: "15 Nov 2024"
  },
  {
    id: 10,
    name: "Patricia Carter",
    role: "Team Lead Dev",
    avatar: "/assets/img/users/user-36.jpg",
    email: "patricia@example.com",
    phone: "(132) 3145 977",
    location: "Colombia",
    rating: "3.0",
    owner: "Daniel Byrne",
    status: "Active",
    company: "Epicurean Delights",
    department: "Engineering",
    createdDate: "10 Dec 2024"
  },
];
