export const leadsData = [
  {
    id: 1,
    name: "Collins",
    companyAvatar: "/assets/img/company/company-01.svg",
    companyName: "BrightWave Innovations",
    phone: "(123) 4567 890",
    email: "anthony@example.com",
    tags: "Closed",
    badgeClass: "badge-success-transparent",
    createdDate: "14 Jan 2024",
    owner: "Hendry Milner",
    source: "Google",
    value: "$1,200"
  },
  {
    id: 2,
    name: "Konopelski",
    companyAvatar: "/assets/img/company/company-02.svg",
    companyName: "Stellar Dynamics",
    phone: "(179) 7382 829",
    email: "brian@example.com",
    tags: "Contacted",
    badgeClass: "badge-purple-transparent",
    createdDate: "21 Jan 2024",
    owner: "Guilory Berggren",
    source: "Referral",
    value: "$2,500"
  },
  {
    id: 3,
    name: "Adams",
    companyAvatar: "/assets/img/company/company-03.svg",
    companyName: "Quantum Nexus",
    phone: "(184) 2719 738",
    email: "harvey@example.com",
    tags: "Lost",
    badgeClass: "badge-danger-transparent",
    createdDate: "20 Feb 2024",
    owner: "Jami Carlile",
    source: "Website",
    value: "$800"
  },
  {
    id: 4,
    name: "Schumm",
    companyAvatar: "/assets/img/company/company-04.svg",
    companyName: "EcoVision Enterprises",
    phone: "(193) 9382 732",
    email: "diane@example.com",
    tags: "Not Contacted",
    badgeClass: "badge-warning-transparent",
    createdDate: "15 Mar 2024",
    owner: "Theresa Wright",
    source: "Direct",
    value: "$1,500"
  },
  {
    id: 5,
    name: "Wisozk",
    companyAvatar: "/assets/img/company/company-05.svg",
    companyName: "Aurora Technologies",
    phone: "(183) 9283 929",
    email: "eugene@example.com",
    tags: "Closed",
    badgeClass: "badge-success-transparent",
    createdDate: "12 Apr 2024",
    owner: "Richard McCoy",
    source: "Campaign",
    value: "$3,200"
  },
  {
    id: 6,
    name: "Heller",
    companyAvatar: "/assets/img/company/company-06.svg",
    companyName: "BlueSky Ventures",
    phone: "(120) 3728 039",
    email: "ray456@example.com",
    tags: "Contacted",
    badgeClass: "badge-purple-transparent",
    createdDate: "20 Apr 2024",
    owner: "Martin Lewis",
    source: "Google",
    value: "$950"
  },
  {
    id: 7,
    name: "Gutkowski",
    companyAvatar: "/assets/img/company/company-07.svg",
    companyName: "TerraFusion Energy",
    phone: "(102) 8480 832",
    email: "murray@example.com",
    tags: "Not Contacted",
    badgeClass: "badge-warning-transparent",
    createdDate: "06 Jul 2024",
    owner: "Newell Egan",
    source: "Referral",
    value: "$1,800"
  },
  {
    id: 8,
    name: "Walter",
    companyAvatar: "/assets/img/company/company-08.svg",
    companyName: "UrbanPulse Design",
    phone: "(162) 8920 713",
    email: "smtih@example.com",
    tags: "Closed",
    badgeClass: "badge-success-transparent",
    createdDate: "02 Sep 2024",
    owner: "Janet Carlson",
    source: "Website",
    value: "$2,100"
  },
  {
    id: 9,
    name: "Hansen",
    companyAvatar: "/assets/img/company/company-09.svg",
    companyName: "Nimbus Networks",
    phone: "(189) 0920 723",
    email: "connie@example.com",
    tags: "Closed",
    badgeClass: "badge-success-transparent",
    createdDate: "15 Nov 2024",
    owner: "Craig Brown",
    source: "Google",
    value: "$4,000"
  },
  {
    id: 10,
    name: "Leuschke",
    companyAvatar: "/assets/img/company/company-10.svg",
    companyName: "Epicurean Delights",
    phone: "(168) 8392 823",
    email: "broaddus@example.com",
    tags: "Lost",
    badgeClass: "badge-danger-transparent",
    createdDate: "10 Dec 2024",
    owner: "Daniel Byrne",
    source: "Direct",
    value: "$500"
  }
];
