export const ordersData = [
  {
    id: 1,
    avatar: "/assets/img/users/user-39.jpg",
    order_id: "ORD-001",
    customer_name: "Rahul Sharma",
    destination_city: "Mumbai",
    destination_state: "Maharashtra",
    destination_country: "India",
    customer_email: "rahul@example.com",
    customer_phone: "+91 9876543210",
    product_name: "Wireless Mouse",
    platform: "Amazon",
    quantity: 2,
    unit_price: 500,
    discount: 50,
    tax: 90,
    payment_status: "paid",
    order_status: "shipped"
  },
  {
    id: 2,
    avatar: "/assets/img/users/user-40.jpg",
    order_id: "ORD-002",
    customer_name: "Sneha Patel",
    destination_city: "Ahmedabad",
    destination_state: "Gujarat",
    destination_country: "India",
    customer_email: "sneha@example.com",
    customer_phone: "+91 9988776655",
    product_name: "Mechanical Keyboard",
    platform: "Flipkart",
    quantity: 1,
    unit_price: 2500,
    discount: 200,
    tax: 414,
    payment_status: "pending",
    order_status: "processing"
  },
  {
    id: 3,
    avatar: "/assets/img/users/user-41.jpg",
    order_id: "ORD-003",
    customer_name: "Amit Kumar",
    destination_city: "Delhi",
    destination_state: "Delhi",
    destination_country: "India",
    customer_email: "amit.k@example.com",
    customer_phone: "+91 9123456789",
    product_name: "Gaming Monitor",
    platform: "Shopify",
    quantity: 1,
    unit_price: 15000,
    discount: 1000,
    tax: 2520,
    payment_status: "paid",
    order_status: "delivered"
  },
  {
    id: 4,
    avatar: "/assets/img/users/user-42.jpg",
    order_id: "ORD-004",
    customer_name: "Priya Singh",
    destination_city: "Bangalore",
    destination_state: "Karnataka",
    destination_country: "India",
    customer_email: "priya.s@example.com",
    customer_phone: "+91 9876512345",
    product_name: "Bluetooth Headphones",
    platform: "Myntra",
    quantity: 3,
    unit_price: 1200,
    discount: 150,
    tax: 620,
    payment_status: "failed",
    order_status: "packed"
  }
];
